### ISSUE TITLE
Idea: Option to convert node_modules folders to PNPM folders

### ISSUE THREAD

**Issue by boehs** [voidcosmos/npkill#111]
Way more space efficient, while not breaking programs ❤️

**Comment by zaldih** [comment]
Thank you for the issue.

pnpm is a great alternative to npm but I think implementing this feature breaks the main purpose of npkill. It would probably be a good option to create another package for that purpose! I'll leave it as an idea.

Since we realised that some important packages could go unnoticed in the results and break programs if deleted. In response to this, we are now displaying a warning for the user to watch out for them.
