### ISSUE TITLE
Enable '--delete-all' feature plz

### ISSUE THREAD

**Issue by mokone91** [voidcosmos/npkill#176]
Hi!
I have a repos with 50+ packages it each, this feature will be very useful for me.
Please enable it

Thanks!
Eldar.

**Comment by zaldih** [comment]
Thank you for opening the issue!

I think it will be a good idea. In fact I've been thinking about it for a while.

At first because of some (very strange and infrequent) bugs it was decided to disable it for security but not to delete it from the code in case someone really needed this feauture, that could clone the project and enable it by modifying the code.

**Now they have been fixed a long time ago so I think it would be a good idea to enable it again :) . I'll work on it soon unless someone wants to go ahead and open a PR.**

## Important 

When you start npkill with --delete-all, the user should get a warning that you are sure you want to run the command and that any node_module found in the path (print path) will be deleted. Require confirmation before proceeding.

**Comment by zaldih** [comment]
@LordZardeck I like the idea of including `-y` to skip confirmations. Over the next week I will try to work and launch this.

**Comment by zaldih** [comment]
This feature has been released in the new version 🎉 
Feel free to leave your feedback or re-open a new issue if there are any problems.

**Comment by LordZardeck** [comment]
@zaldih Got to use the update for the first time, and it's a nice improvement. One thing I didn't think to clarify, would there be a way to either not show the UI, or have it auto-exit when using delete all? It's a _minor_ annoyance to have to manually close out.
