### ISSUE TITLE
[Feature request] Add loading indicator to 'delete in progress' state

### ISSUE THREAD

**Issue by grudus** [voidcosmos/npkill#58]
Hi!
Thanks to your project, I've deleted some heavy node_modules and that's great, but I found a possible improvement:
When you try to delete a large directory, the removing process can take a few seconds, and there is no interaction from the app and it seems like it doesn't respond (I thought Space isn't working and I tried Enter or cmd+enter),

It will be nice to add some kind of text (or progress bar?) to show user, that action is performed

**Comment by zaldih** [comment]
Hello!
**Thank you for your comment, and sorry for the delay.**

Of course it is a very interesting feature that in fact I was able to develop a while back ( #45 ).

But due to lack of time, we have not been able to launch a new version with that feature (and other improvements).

Luckily now we have life again and soon we will launch a new one :)
