### ISSUE TITLE
Extend exclude option to handle timestamps

### ISSUE THREAD

**Issue by cycle4passion** [voidcosmos/npkill#76]
Currently

-E, --exclude option accepts directories quotes to exclude. It would be nice to be able to do

-E 30 

Which would exclude any N_M dirs with modifications of any enclosed files in the last 30 days. This would be a nice way not to npkill active work.

**Comment by zaldih** [comment]
I have only recently started working on it!
However I think the correct approach is somewhat more complex: look for when the most recent file was edited in the workspace (and not just the node_module).

That's why the filtering will be done on node instead of directly on the find command

https://github.com/voidcosmos/npkill/issues/64#issuecomment-1273637895
