### ISSUE TITLE
Surprising key bindings

### ISSUE THREAD

**Issue by ranisalt** [voidcosmos/npkill#77]
**Is your feature request related to a problem? Please describe.**
This utility currently uses Space as the key to delete files. It goes against virtually all other file list utilities (e.g. ranger file manager, ncmpcpp MPD client) that use space to tag an item, then another key binding (usually d) to delete tagged items.

It might lead to surprises if an user does not throughly read the instructions and expect same bindings as other apps.

**Describe the solution you'd like**
Change the Space key binding to mark an entry, and move deletion to another key.

**Additional context**
- [ranger default config](https://github.com/ranger/ranger/blob/master/ranger/config/rc.conf#L395)
- [ncmpcpp key bindings](https://pkgbuild.com/~jelle/ncmpcpp/) (scroll down to Keys - Browser)

**Comment by NyaGarcia** [comment]
Hi! Sorry for the prolonged wait, haven't had much spare time in a long while :sweat_smile:

We decided to use the Space key because it's such a large, easily accessible key. It's true that it isn't the norm for deleting, but I personally like it and I think that it's easier to use than d, for example. Plus, there are many other tools that have completely random, unique key bindings (look at the Vim guys, for example :laughing: )

Regarding what you say about users might getting surprised, the instructions are pretty simple and show up as soon as you run Npkill (and are highlighted in a very obvious yellow, so they're hard to miss), so I don't think anyone should have any doubts about which keys to use... 

So for now, I think we're going to keep things the way they are. However, we could consider changing it if this becomes a demanded feature. Thank you for your suggestion though, it's appreciated :smile:
