### ISSUE TITLE
--delete-all deletes non NPM data

### ISSUE THREAD

**Issue by agonbina** [voidcosmos/npkill#9]
It deleted all the content that I had in my desktop (images, videos, etc) and screwed up a lot of my tooling. 

I do not know where the bug is but I can with certainty tell you that it does not delete only node_modules and npm packages. 

I only have to blame myself for trusting such a flag in the first place, but it may be nice to add a warning sign that this is performing a hard delete on whatever it finds.

**Comment by zaldih** [comment]
First of all, I deeply regret what happened.
Please, could you provide me with all the possible information?
- Program version (npkill -v)
- OS
- The steps prior to the event
- If possible, the route from which you ran npkill
- Remember if during the event, all the directories in the list were shown?

Before launching the first version to the public, we did thousands of tests to test that none of this could happen.

Are you completely sure that the problem has been caused by npkill?

**Comment by duongdev** [comment]
Yes, all of my projects are gone. Just installed latest version (npkill@0.2.4). Ran `npmkill -D` on home directory.

**Comment by duongdev** [comment]
It deleted not only my projects but everything under my home. The `Projects/targeek` still there because I was running a web server there while running `npmkill -D`.

![image](https://user-images.githubusercontent.com/9253690/62935823-51958700-bdf2-11e9-9772-c45c967c5185.png)

**Comment by NyaGarcia** [comment]
First of all, we'd like to thank you for opening and participating in this issue. 

We have not been able to find any evidence of npkill deleting any files apart from node_modules, nor have we been able to replicate this behaviour (not for lack of trying.)

What we have realised, after hours of testing, is that some applications, such as Visual Studio Code, Discord, Postman etc. have their own node_modules directories that enable them to work correctly. Therefore, when using npkill's --delete-all flag, these node_modules directories are also deleted. This can cause the aforementioned applications (and any other application that stores its dependencies in a node_modules directory) to fail or have unexpected behaviours, like messing up VS tooling. 

Despite the fact that this is annoying and can cause a great deal of trouble, the --delete-all flag is working as expected, since it is searching for and automatically deleting **every single node_modules** directory it finds.

Even so, we have reached the conclusion that this flag can be dangerous and can cause problems. Therefore, we have chosen to remove it from npkill.

**Comment by shennan** [comment]
Perhaps a list of everything that would be deleted as a result of this flag as a sanity check, then requiring a simple "Y" input to confirm such deletions? It's pretty annoying having to cycle through everything with space bar. And then if one takes longer, you need to cycle back up to check it's been deleted before quitting the runtime.
